services:
  jupyter:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    volumes:
      - ./notebook:/tf
      - jupyter_config_data:/root/.jupyter
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    profiles:
      - with_notebook

  server:
    image: tensorflow/serving
    volumes:
      - ./notebook/char_recog_model/:/models/char_recog_model/1
    environment:
      - MODEL_NAME=char_recog_model
    ports:
      - "8501:8501"

  webapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - node_modules_data:/app/node_modules
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"

volumes:
  jupyter_config_data:
  node_modules_data:
