services:
  tsfw:
    build: .
    volumes:
      - ./app:/app
      - ./notebooks:/tf
      - ./data:/tf/data
      - jupyter_config_data:/root/.jupyter
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  jupyter_config_data:
